apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "apty-static.fullname" . }}
  labels:
    {{- include "apty-static.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "apty-static.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "apty-static.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: nginx
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80
              name: http
          env:
            - name: ENV_NAME
              value: "{{ .Values.env }}"
          readinessProbe:
            httpGet:
              path: "/"
              port: http
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
          resources:
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
